PetHotel/Areas/Client/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Core.Contracts;

namespace PetHotel.Areas.Client.Controllers
{
    [AllowAnonymous]
    [Area("Client")]
    public class GalleryController : Controller
    {
        private IWebHostEnvironment hostingEnv;
        private readonly IGalleryService service;
        public GalleryController(IWebHostEnvironment _hostingEnv, IGalleryService _service)
        {
            this.hostingEnv = _hostingEnv;
            this.service = _service;
        }
        [Route("Index")]
        
        public IActionResult Index()
        {
            return View();
        }


        [Route("DisplayGallery")]
       
        public IActionResult DisplayGallery()
        {
            var imageList = service.GetAll();

            var model = service.GetIndexModel(imageList);

            return View(model);
        }
        [Route("Details")]
        
        public async Task <IActionResult> Details(int? id)
        {
            if (id == null) return RedirectToAction(nameof(DisplayGallery));

            var image = await service.GetById(id ?? 0);

            if (image == null) return RedirectToAction(nameof(DisplayGallery));

            var model = service.GetDetailsModel(image);

            return View(model);
        }
    }
}

PetHotel/Areas/Client/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Common;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.HotelModels;
using System.Security.Claims;

namespace PetHotel.Areas.Client.Controllers
{
    [Authorize]
    [Area("Client")]
    public class HotelController : Controller
    {
        private readonly IHotelService service;
        private readonly IUserService userService;
        
        public HotelController(IHotelService _service, IUserService _userService)
        {
            this.service = _service;
            this.userService = _userService;
          
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("Add")]
        [HttpGet]
        public async Task<IActionResult> Add(int Id)//this is the id of the pet
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //check if pet is owned by the logged in user.
            string loggedUserId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await userService.UserOwnsPet(loggedUserId, Id)) return RedirectToAction(nameof(AllMine));

            return View(await service.GetGuestToAddAsync(Id));
        }

        [Route("Add")]
        [HttpPost]
        public async Task<IActionResult> Add(AddGuestViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            
                await service.AddGuestAsync(model);

                return RedirectToAction(nameof(AllMine));
        }

        [Route("AllMine")]
        /*[HttpPost]*/
        public async Task<IActionResult> AllMine()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value; 
            
                var allMyPetsInHotel = await service.GetMyAllGuestsAsync(userId);
                return View(allMyPetsInHotel);
        }


        [Route("CancelReserv")]

        public async Task<IActionResult> CancelReserv(int? id) //this is the id of the reservation
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //user is checked if they own the pet guest 
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await service.IsGuestOwnedByUser(id ?? 0, userId)) return RedirectToAction("Index", "Home");

            await service.CancelHotelStayAsync(id ?? 0);

               return RedirectToAction(nameof(AllMine));
        }

        [Route("EditReservation")]
        [HttpGet]
        public async Task<IActionResult> EditReservation(int? Id) //this is the id of the reservation
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //user is checked if they own the pet guest 
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await service.IsGuestOwnedByUser(Id ?? 0, userId)) return RedirectToAction("Index", "Home");

            return View(await service.GetGuestToEditAsync(Id ?? 0));
        }



        [Route("EditReservation")]
        [HttpPost]
        public async Task<IActionResult> EditReservation(AddGuestViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            
                await service.EditGuestAsync(model);

                return RedirectToAction(nameof(AllMine));
            

        }
    }
}

PetHotel/Areas/Client/Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using PetHotel.Common;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.PetModels;
using System.Security.Claims;

namespace PetHotel.Areas.Client.Controllers
{
    [Authorize]
    [Area("Client")]
    public class PetController : Controller
    {
        private readonly IPetService service;
        private readonly IMemoryCache cache;
        private readonly IUserService userService;
        public PetController(IPetService _service, IMemoryCache _cache, IUserService _userService)
        {
            this.service = _service;
            this.cache = _cache;
            this.userService = _userService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Route("Create")]
        [HttpGet]

        public async Task<IActionResult> Create()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");
            ViewData["PetTypeId"] = new SelectList(await GetTypes(), "Id", "Name");

            return View();
        }

        [Route("Create")]
        [HttpPost]

        public async Task<IActionResult> Create(CreatePetViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["PetTypeId"] = new SelectList(await GetTypes(), "Id", "Name");
                return View(model);
            }

            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;

            await service.AddPetAsync(model, userId);
            return RedirectToAction("Profile", "User");
        }

        [Route("Delete")]
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult>Delete(int Id)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;

            if (await userService.UserOwnsPet(userId, Id)) await service.DeletePetAsync(Id);

           
            return RedirectToAction("Profile", "User");
        }
        [Route("Edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;

            if (!await userService.UserOwnsPet(userId, Id)) return RedirectToAction("Profile", "User"); 


            var model = await service.GetPetAsync(Id);
            ViewData["PetTypeId"] = new SelectList(await GetTypes(), "Id", "Name");
           return View(model);
            
            
        }

        [Route("Edit")]
        [HttpPost]
        public async Task<IActionResult> Edit(CreatePetViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["PetTypeId"] = new SelectList(await GetTypes(), "Id", "Name");
                return View(model); 
            }
            
                await service.EditPetAsync(model);
                return RedirectToAction("Profile", "User");
            
           
        }


        private async Task<IEnumerable<PetTypeViewModel>> GetTypes() 
            => await service.GetAllPetTypesAsync();
        
    }
}

PetHotel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models;
using System.Diagnostics;

namespace PetHotel.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly IHomeService service;

        public HomeController(IHomeService _service)
        {
            this.service = _service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Prices()
        {
            var model = await service.GetPricesAsync();
            
            return View(model);
        }
    }
}

PetHotel/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.UserModels;
using System.Security.Claims;

namespace PetHotel.Controllers
{
    /// <summary>
    /// UserController handles login, register and logout functions by calling UserService.
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService service;
        public UserController(IUserService _service)
        {
            service = _service;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View(new RegisterViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View( model);
            }

            try
            {
                await service.RegisterNewUserAsync(model);
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                return View(model);
            }
            
            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult>Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await service.LoginUserAsync(model);
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Logout. Doesn't need to check if the user is logged in
        /// because of the [Authorize] attribute for this controller.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await service.SignOutUserAsync();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// View the logged user's profile information and pets.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            
            try
            {
                var userProfile = await service.GetProfileAsync(userId!); //userId can't be null because the user is logged
                return View(userProfile);
            }
            catch (ArgumentNullException ne)
            {
                //TODO error page redirect
                return BadRequest(ne.Message);
            }
        }
    }
}

PetHotel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.AdministratorRoleName) ?? false)
    {
        Layout = "/Views/Shared/_LayoutAdmin.cshtml";
    }
    @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.EmployeeRoleName) ?? false)
    {
        Layout = "/Views/Shared/_LayoutClient.cshtml";
    }
}
<head>
    <style>
        h1 {
            text-align: center;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        div {
            text-align: center;
        }

        a:link {
            color: green;
            background-color: transparent;
            text-decoration: none;
        }

        a:visited {
            color: pink;
            background-color: transparent;
            text-decoration: none;
        }

        a:hover {
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active {
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
    </style>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>
    <div style="background-image: url('images/pet-first-aid-banner-1400x815.jpg');
  background-size: cover; height:400px; padding-top:80px;">

        <h5 class="display-4" style="color:ghostwhite"><b>The Cats Dogs and Crocs</b></h5>
        <h5 class="display-4" style="color:ghostwhite"><b>Hotel</b></h5>
        <section class="home-page">
            @if (this.User?.Identity?.IsAuthenticated ?? false)
            {
                <h1 class="display-4" style="color:ghostwhite">Hi @this.User.Identity.Name</h1>

                @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.AdministratorRoleName) ?? false)
                {
                    <h1 class="display-4"> You have admin rights</h1>
                }
            }
        </section>
    </div>
    <div style="background-size: cover; height:50px; padding-top:80px;"></div>

    <div class="w3-container">


        <div class="w3-card-4" style="width:50%; float:left;">
    <header class="w3-container w3-teal">
      <h1>About Us</h1>
    </header>

    <div class="w3-container">
      <p>We are a great team filled with proffessionals who love pets. We are conviniently located in Sofia.</p>
    </div>

            <footer class="w3-container w3-teal">
      <a class="nav-link text-dark" asp-area="Client" asp-controller="Location" asp-action="MAP">
                <b>You can find us here</b>
      </a>
    </footer>
  </div>
        <div class="w3-card-4" style="width:50%; float:left; ">
            <header class="w3-container w3-teal">
      <h1>Our Services</h1>
    </header>

    <div class="w3-container">
      <p>We'll look after your cat, dog or even crocodile 365 days a year. We work every holiday so you can ejoy yours.</p>
    </div>

            <footer class="w3-container w3-teal">
                <a class="nav-link text-dark" asp-controller="Home" asp-action="Prices">
                    <b>See our prices</b>
                </a>
    </footer>
  </div>
</div>




<div class="w3-container">
        <div class="w3-panel w3-card">
            <p><h2 style="color:ghostwhite">Gallery</h2></p>
            <p>
                <a class="nav-link text-dark" asp-area="Client" asp-controller="Gallery" asp-action="DisplayGallery">
                    <b>Click Here To Check Our Gallery</b>

                </a>
            </p>
        </div>
</div>

@{

    if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.UserRoleName) ?? false)
    {
       <div class="w3-container">
        <div class="w3-panel w3-card">
                <h1 class="display-4" style="color:ghostwhite"> Control your reservations and pets</h1>
            <a class="nav-link text-dark" asp-area="Client" asp-controller="Pet" asp-action="Create">
                <b>Add a new pet</b>

            </a>
            <a class="nav-link text-dark" asp-area="Client" asp-controller="User" asp-action="MyPets">
                <b>Make a reservation</b>

            </a>
            <a class="nav-link text-dark" asp-area="Client" asp-controller="Hotel" asp-action="AllMine">
                <b>My reservations</b>

            </a>
           
           
        </div>
        </div>
    }
        else if (!User.Identity.IsAuthenticated && !this.User.IsInRole(PetHotel.Common.GlobalConstants.EmployeeRoleName))
        {
            <div class="w3-container">
        <div class="w3-panel w3-card">
                <h1 class="display-4" style="color:ghostwhite"> Don't have an account?</h1>
            <a class="nav-link text-dark" asp-area="Client" asp-controller="User" asp-action="Register">
                <b>Create one here</b>

            </a>
            
           
        </div>
        </div>
        }

        else if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.EmployeeRoleName) ?? false)
        {
            <div class="w3-container">
        <div class="w3-panel w3-card">
                <h1 class="display-4" style="color:ghostwhite"> You have Employee rights</h1>
            <a class="nav-link text-dark" asp-area="Employee" asp-controller="Hotel" asp-action="ControlMenu">
                <b>Reservations control panel</b>

            </a>
            
           
        </div>
        </div>
        }

         else if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.AdministratorRoleName) ?? false)
        {
            <div class="w3-container">
        <div class="w3-panel w3-card">
                <h1 class="display-4" style="color:ghostwhite"> You have Admin rights</h1>
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Administrator" asp-action="Profiles">
                <b>Accounts control panel</b>

            </a>
            
           
        </div>
        </div>
        }
}    
    <div style="background-size: cover; height:240px; padding-top:80px;"></div>
   
</body>

PetHotel/Views/Home/Prices.cshtml
@model ICollection<PetHotel.Core.Models.HomeModels.PricesViewModel>
@{
    ViewData["Title"] = "Prices";
     @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.EmployeeRoleName) ?? false)
    {
        Layout = "/Views/Shared/_LayoutClient.cshtml";
    }
    @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.UserRoleName) ?? false)
    {
        Layout = "/Views/Shared/_Layout.cshtml";
    }
    if (this.User.Identity.IsAuthenticated == false)
    {
        Layout = "/Views/Shared/_Layout.cshtml";
    }

    @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.AdministratorRoleName) ?? false)
    {
        Layout = "/Views/Shared/_LayoutAdmin.cshtml";
    }
}

<head>
<style>
img {
  width:400px;
  height:300px;
}
</style>
</head>
<body>
    <img src="~/Images/rooms.jpg"  width="400" height="300">
    <div>
 <h2>Price List:</h2>
    @foreach (var item in Model)
    {
              <ul>
               <li>@item.Title - @item.Price.ToString("0.00") lv. Per Day</li>
              </ul>
    }
    </div>
    
</body>