PetHotel/Areas/Client/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Common;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.HotelModels;
using System.Security.Claims;

namespace PetHotel.Areas.Client.Controllers
{
    [Authorize]
    [Area("Client")]
    public class HotelController : Controller
    {
        private readonly IHotelService service;
        private readonly IUserService userService;
        
        public HotelController(IHotelService _service, IUserService _userService)
        {
            this.service = _service;
            this.userService = _userService;
          
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("Add")]
        [HttpGet]
        public async Task<IActionResult> Add(int Id)//this is the id of the pet
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //check if pet is owned by the logged in user.
            string loggedUserId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await userService.UserOwnsPet(loggedUserId, Id)) return RedirectToAction(nameof(AllMine));

            return View(await service.GetGuestToAddAsync(Id));
        }

        [Route("Add")]
        [HttpPost]
        public async Task<IActionResult> Add(AddGuestViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            
                await service.AddGuestAsync(model);

                return RedirectToAction(nameof(AllMine));
        }

        [Route("AllMine")]
        /*[HttpPost]*/
        public async Task<IActionResult> AllMine()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value; 
            
                var allMyPetsInHotel = await service.GetMyAllGuestsAsync(userId);
                return View(allMyPetsInHotel);
        }


        [Route("CancelReserv")]

        public async Task<IActionResult> CancelReserv(int? id) //this is the id of the reservation
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //user is checked if they own the pet guest 
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await service.IsGuestOwnedByUser(id ?? 0, userId)) return RedirectToAction("Index", "Home");

            await service.CancelHotelStayAsync(id ?? 0);

               return RedirectToAction(nameof(AllMine));
        }

        [Route("EditReservation")]
        [HttpGet]
        public async Task<IActionResult> EditReservation(int? Id) //this is the id of the reservation
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName)) return RedirectToAction("Index", "Home");

            //user is checked if they own the pet guest 
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            if (!await service.IsGuestOwnedByUser(Id ?? 0, userId)) return RedirectToAction("Index", "Home");

            return View(await service.GetGuestToEditAsync(Id ?? 0));
        }



        [Route("EditReservation")]
        [HttpPost]
        public async Task<IActionResult> EditReservation(AddGuestViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            
                await service.EditGuestAsync(model);

                return RedirectToAction(nameof(AllMine));
            

        }
    }
}

PetHotel/Areas/Client/Controllers/ImageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Common;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.GalleryModels;

namespace PetHotel.Areas.Client.Controllers
{
    [Area("Client")]
    [Authorize]
    public class ImageController : Controller
    {
        private readonly ICloudinaryImageUpload imageUpload;
        public ImageController(ICloudinaryImageUpload _imageUpload)
        {
            this.imageUpload = _imageUpload;
        }

        [HttpGet]
        [Route("UploadNewImage")]
        public IActionResult UploadNewImage()
        {
            if (!User.IsInRole(GlobalConstants.EmployeeRoleName)) return RedirectToAction("Index", "Home");

            var model = new UploadModel();

            return View(model);
        }

        [HttpPost]
        [Route("UploadNewImage")]
        public async Task<IActionResult> UploadNewImage(UploadModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await imageUpload.UploadPicture(model);
            return RedirectToAction("DisplayGallery", "Gallery");

        }
    }
}

PetHotel/Areas/Client/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;

namespace PetHotel.Areas.Client.Controllers
{
    [Area("Client")]
    public class LocationController : Controller
    {
        [Route("Map")]
        public IActionResult MAP()
        {
            return View();
        }
    }
}

PetHotel/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetHotel.Core.Contracts;
using PetHotel.Core.Models.UserModels;
using System.Security.Claims;

namespace PetHotel.Controllers
{
    /// <summary>
    /// UserController handles login, register and logout functions by calling UserService.
    /// </summary>
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService service;
        public UserController(IUserService _service)
        {
            service = _service;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View(new RegisterViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View( model);
            }

            try
            {
                await service.RegisterNewUserAsync(model);
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                return View(model);
            }
            
            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult>Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await service.LoginUserAsync(model);
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(string.Empty, ae.Message);
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Logout. Doesn't need to check if the user is logged in
        /// because of the [Authorize] attribute for this controller.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await service.SignOutUserAsync();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// View the logged user's profile information and pets.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            string userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)!.Value;
            
            try
            {
                var userProfile = await service.GetProfileAsync(userId!); //userId can't be null because the user is logged
                return View(userProfile);
            }
            catch (ArgumentNullException ne)
            {
                //TODO error page redirect
                return BadRequest(ne.Message);
            }
        }
    }
}

PetHotel/Views/Shared/AccessDenied.cshtml
<!DOCTYPE html>
<html>
<head>
<title>Access Denied</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta charset="UTF-8">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
<div class="w3-display-middle">
<h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
<hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
<h3 class="w3-center w3-animate-right">You dont have permission to view this site.</h3>
<h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
<h6 class="w3-center w3-animate-zoom">error code:403 forbidden</h6>
</div>
</body>
</html>

PetHotel/Views/Shared/_Layout.cshtml
@using PetHotel.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetHotel.styles.css" asp-append-version="true" />
    
    <style>
        body {
            background: linear-gradient(to top left, #7393B3, #C0C0C0);
            background-repeat: cover;
            color: black;
        }

        .card {
            /* Add shadows to create the "card" effect */
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }
            /* On mouse-over, add a deeper shadow */
            .card:hover {
                box-shadow: 0 16px 32px 0 #0a0603;
            }
        /* Add some padding inside the card container */
        .container {
            padding: 4px 32px;
        }

        .btn {
            display: inline-block;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            border: none;
            border-radius: 30px;
            box-shadow: 0 5px #999;
        }
        
        .button:active {
           
            box-shadow: 0 4px #666;
            transform: translateY(4px);
        }


            li a {
                display: block;
                color: #90EE90;
                text-align: center;
                padding: 1px 1px;
                text-decoration: none;
            }

                li a:hover {
                    background-color: lightgrey;
                }

        .footer {
            position: relative;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 5px;
            background-color: green;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-#90EE90 box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                          
                        </li>
                        <li class="nav-item">
                           
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Location" asp-action="MAP">Contacts</a>
                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Gallery" asp-action="DisplayGallery">Gallery</a>
                        </li>

                        @if (this.User?.IsInRole(PetHotel.Common.GlobalConstants.UserRoleName) ?? false)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Hotel" asp-action="AllMine">My reservations</a>
                        </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Client" asp-controller="User" asp-action="MyPets">Make a reservations</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container position-relative">
            &copy; 2022 - PetHotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>

PetHotel/Views/Shared/_LayoutAdmin.cshtml
@using PetHotel.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetHotel.styles.css" asp-append-version="true" />
   
    <style>
        body {
            background: linear-gradient(to top left, #7393B3, #CF9FFF);
            background-repeat: cover;
            color: black;
        }

        .card {
            /* Add shadows to create the "card" effect */
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }
            /* On mouse-over, add a deeper shadow */
            .card:hover {
                box-shadow: 0 16px 32px 0 #0a0603;
            }
        /* Add some padding inside the card container */
        .container {
            padding: 4px 32px;
        }

        .btn {
            display: inline-block;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            border: none;
            border-radius: 30px;
            box-shadow: 0 5px #999;
        }
        /*   .button:hover {
                    background-color: #3e8e41
                }*/
        .button:active {
            /*  background-color: #3e8e41;*/
            box-shadow: 0 4px #666;
            transform: translateY(4px);
        }

        

            li a {
                display: block;
                color: #90EE90;
                text-align: center;
                padding: 1px 1px;
                text-decoration: none;
            }

                li a:hover {
                    background-color: lightgrey;
                }

        .footer {
            position: relative;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 5px;
            background-color: green;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-#90EE90 box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Administrator" asp-action="Profiles">View All Profiles</a>
                            </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container position-relative">
            &copy; 2022 - PetHotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>

PetHotel/Views/Shared/_LayoutClient.cshtml
@using PetHotel.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetHotel.styles.css" asp-append-version="true" />
    @*    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>*@
    <style>
        body {
            background: linear-gradient(to top left, #7393B3, #DE3163);
            background-repeat: cover;
            color: black;
        }

        .card {
            /* Add shadows to create the "card" effect */
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }
            /* On mouse-over, add a deeper shadow */
            .card:hover {
                box-shadow: 0 16px 32px 0 #0a0603;
            }
        /* Add some padding inside the card container */
        .container {
            padding: 4px 32px;
        }

        .btn {
            display: inline-block;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            border: none;
            border-radius: 30px;
            box-shadow: 0 5px #999;
        }
        
        .button:active {
            /*  background-color: #3e8e41;*/
            box-shadow: 0 4px #666;
            transform: translateY(4px);
        }

        

            li a {
                display: block;
                color: #90EE90;
                text-align: center;
                padding: 1px 1px;
                text-decoration: none;
            }

                li a:hover {
                    background-color: lightgrey;
                }

        .footer {
            position: relative;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 5px;
            background-color: green;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-#90EE90 box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Employee" asp-controller="Hotel" asp-action="ControlMenu">Manage reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Employee" asp-controller="Image" asp-action="UploadNewImage">Upload To Gallery</a>
                        </li>
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container position-relative">
            &copy; 2022 - PetHotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>